### ISSUE TITLE
No entry into round available

### ISSUE THREAD

**Issue by Vasily2013** [FTL13/FTL13#3676]
Round ID: 1800
Round refused to let players enter from the ready menu or progress beyond it even though round was 3+ hours in progress.

**Comment by crossedfall** [comment]
Logs have been synced with the external server for those with access. I'll check to see if I can spot anything obvious as to why that happened.

**Comment by crossedfall** [comment]
Looks like it was a problem with the April fools map somehow still being in rotation despite already being removed. When we forced the server to recompile and changed the map out for something else the issue was resolved. 

No further problems have been detected and everything seems to be running smoothly again. Going to close this for now as a result.
