### ISSUE TITLE
Default Supermatter setup is kinda shit

### ISSUE THREAD

**Issue by Psyentific** [FTL13/FTL13#740]
**Problem Description**:
The roundstart supermatter layout is kinda shit, resulting in low power generation and a tendency to explode if mishandled. The tendency to explode is directly caused by unrobust cold loops (ie not filled with plasma, pump not turned on)

**What did you expect to happen**: 
Turn on all the pumps and filters
Wrench the cans where they lay
Turn on the gas circulation in the engine core
Flip the switch
Adequate power 5ever

**What happened instead**:
Turn on all the pumps and filters
Wrench the cans where they lay
Turn on the gas circulation in the engine core
Flip the switch
Cold loop runs a bit hot
Shitty power generation

**Why is this bad/What are the consequences:**
Basically, it means you need to know what you're doing and how the SM/TEG works in order to be a decent engi, contrast to the singulo/tesla which can be set up off the initial map and done by rote.

This creates a barrier to entry, and a lot of people don't really want to play engi because they feel they have to fuck with the SM to get it 'right'.

**Suggested fix:**
1) Replace the N2 canisters in the TEG engine room with Plasma for the space loop and N2O for the hot loop. This is a 'good enough' config that also guides rookie engis. As long as the space loop is full of plasma, you have to try pretty hard to explode the SM.

2) If possible, default the space loop pump and hot loop filters to maximum throughput.

**Comment by ninjanomnom** [comment]
Even in tg where rounds are much shorter than ours, initial setups for things like the engine and atmosia are purposefully left unoptimized so they have things to do for a while.

**Comment by Shuffl3** [comment]
I dont think these are bad consequences. A decent engi should know how the SM/TEG works. Having a poopy initial setup gives engis a reason to experiment and become better. And when engineers have to justify their setups to each other it increases the knowledge base of the pool. Which makes it more likely that new engineers will have someone knowledgeable to show them the ropes. 

QoLing the initial setup to something that can be done rote will rot the cadre thats formed around the challenge of gettin gud.

Sides, cold loops not really the problem. Its splody and the power gen is low because of that single ventpump out of the core and the high pipe volume between it and the TEG input.
