### ISSUE TITLE
Planetside lighting is broken again

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#963]
It's all darkness

**Comment by AuroranAI** [comment]
The good news is that this isn't lighting
The bad news is it's related to how planets generate turfs, and the icons being all screwed up.
Sand/water/snow's issue is somehow icon_state is getting set to sand[variation] instead of sand_[variation]
Grass/grass edges/water edges seems to have a similar issue, but for some reason it's icon_state is getting set to default (asteroid for grass, e_0 for edges) instead of having it get set. (Snow is also somehow having this happen, whereas sand wasn't?)
Water and snow are also somehow getting variables like snow10, when there's only one possible snow tile in planet.dmi
Not entirely related, but the variable baseturf seems to be defaulting to space instead of sand like it should; that might be what's causing the voids in front of cargo?
